const fs = require('fs');
let content = fs.readFileSync('src/app/(dashboard)/pos/pos-client.tsx', 'utf8');

const fullCountries = `<option value="+213">+213 (Algeria)</option>
                          <option value="+244">+244 (Angola)</option>
                          <option value="+229">+229 (Benin)</option>
                          <option value="+267">+267 (Botswana)</option>
                          <option value="+226">+226 (Burkina Faso)</option>
                          <option value="+257">+257 (Burundi)</option>
                          <option value="+237">+237 (Cameroon)</option>
                          <option value="+238">+238 (Cape Verde)</option>
                          <option value="+236">+236 (Central African Republic)</option>
                          <option value="+235">+235 (Chad)</option>
                          <option value="+269">+269 (Comoros)</option>
                          <option value="+242">+242 (Congo)</option>
                          <option value="+243">+243 (DR Congo)</option>
                          <option value="+253">+253 (Djibouti)</option>
                          <option value="+20">+20 (Egypt)</option>
                          <option value="+240">+240 (Equatorial Guinea)</option>
                          <option value="+291">+291 (Eritrea)</option>
                          <option value="+268">+268 (Eswatini)</option>
                          <option value="+251">+251 (Ethiopia)</option>
                          <option value="+241">+241 (Gabon)</option>
                          <option value="+220">+220 (Gambia)</option>
                          <option value="+233">+233 (Ghana)</option>
                          <option value="+224">+224 (Guinea)</option>
                          <option value="+245">+245 (Guinea-Bissau)</option>
                          <option value="+225">+225 (Ivory Coast)</option>
                          <option value="+254">+254 (Kenya)</option>
                          <option value="+266">+266 (Lesotho)</option>
                          <option value="+231">+231 (Liberia)</option>
                          <option value="+218">+218 (Libya)</option>
                          <option value="+261">+261 (Madagascar)</option>
                          <option value="+265">+265 (Malawi)</option>
                          <option value="+223">+223 (Mali)</option>
                          <option value="+222">+222 (Mauritania)</option>
                          <option value="+230">+230 (Mauritius)</option>
                          <option value="+212">+212 (Morocco)</option>
                          <option value="+258">+258 (Mozambique)</option>
                          <option value="+264">+264 (Namibia)</option>
                          <option value="+227">+227 (Niger)</option>
                          <option value="+234">+234 (Nigeria)</option>
                          <option value="+250">+250 (Rwanda)</option>
                          <option value="+239">+239 (Sao Tome)</option>
                          <option value="+221">+221 (Senegal)</option>
                          <option value="+248">+248 (Seychelles)</option>
                          <option value="+232">+232 (Sierra Leone)</option>
                          <option value="+252">+252 (Somalia)</option>
                          <option value="+27">+27 (South Africa)</option>
                          <option value="+211">+211 (South Sudan)</option>
                          <option value="+249">+249 (Sudan)</option>
                          <option value="+255">+255 (Tanzania)</option>
                          <option value="+228">+228 (Togo)</option>
                          <option value="+216">+216 (Tunisia)</option>
                          <option value="+256">+256 (Uganda)</option>
                          <option value="+260">+260 (Zambia)</option>
                          <option value="+263">+263 (Zimbabwe)</option>`;

content = content.replace(/<option value="\+250">\+250 \(Rwanda\)<\/option>[\s\S]*?<option value="\+233">\+233 \(Ghana\)<\/option>/g, fullCountries);
fs.writeFileSync('src/app/(dashboard)/pos/pos-client.tsx', content);
